version: "3"

services:
  dashboard:
    build: .
    image: insgreeb-pro/faustine
    volumes:
      - static:/app/out
  ui:
    image: nginx
    depends_on:
      - dashboard
    volumes:
      - static:/usr/share/nginx/html
    ports:
      - 3315:80

volumes:
  static:
