name: Deploy to Insgreeb Server

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: |
            cd ~/faustine
            git pull origin master
            docker-compose up -d --build --remove-orphans
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_ROOT }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
